- .github/CONTRIBUTING.md
- README.md
> Updated files

- Sorting/Quicksort/Quicksort.cpp
- Created a new Quicksort folder in sorting and added quicksort algo in C++
Closes: #20 
> Added Quicksort Algo

- Sorting/SelectionSort/main.py
Closes: #[issue number that will be closed through this PR]
> Create main.py in SelectionSort

- Sorting/insertion_sort.c
> Insertion Sort

- Searching/Linear_Search/Linear_search.c
- Implemented linear search in C.
Closes: #29
implemented linear search in c language.
- [ x] New feature (non-breaking change which adds functionality)
-  [ x] My code follows the guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly whereever it was hard to understand.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.
> implemented linear search in c language

- Graphs/BFS Traversal/BFS.cpp
- Graphs/DFS Traversal/DFS.cpp
- Adding bfs and bfs traversal in c++
Closes: #31 
I have added BFS and DFS traversal folder inside Graph folder
> Adding BFS and DFS traversal in Graphs in c++

- Sorting/MergeSort/MergeSort.c
Closes: #36 
Write Algorithm For Merge Sort  in C language
- Tested the code on my PC 
- Tested the code on online IDE's also
> Merge Sort in c

- Searching/Binary_Search/BinarySearch.cpp
Implemented Binary Search Algorithm in C++
closes: #33 
> Binary Search Algo

- Sorting/ShellSort/ShellSort.py
> Add Shell Sort using Python (Issue #49)

- Searching/Linear_Search/LinearSearch.java
Closes: #29 
Write Algorithm For Linear Search  in Java language
- Tested the code on my PC 
- Tested the code on online IDE's also
> Linear Search in Java

- Sorting/Counting Sort/counting_sort.cpp
Fixes #61
Written an code for sorting using count sort
> Counting Sort

- Sorting/Quicksort/Quicksort.py
Closes: #[issue number that will be closed through this PR]
> Add Quicksort Python Implementation

- Searching/Binary_Search/BinarySearch.c
Closes: (#33) 
Write the algorithm for Binary Search in C Language
> Binary Search in C language

- Searching/Binary_Search/BinarySearch.java
> Binary Search in Java language #33

- Sorting/BubbleSort/BubbleSort.c++
- Sorting/BubbleSort/BubbleSort.java
Closes: (#52 )
Write the Algorithm for Bubble Sort in C++ and Java
<!-- ## How Has This Been Tested?
- Run the code on my PC
- Run the code on online IDE's
> Bubble Sort in C++ and Java

- Queue/Implementation_of_queue_using_array/Implementation_of_queue_using_array.cpp
Closes: #[issue number that will be closed through this PR]
> Implementation of Queue using array

- Graphs/Tarjans_Algorithm/Tarjans_Algorithm.cpp
Issue : #79 
Closes: #79 
I have added the implementation of Tarjan's Algorithm to find strongly connected components in C++.
I have verified the code with sample input-output.
> Added Tarjan's Algorithm Implementation

- Queue/QueueImp.java
- Queue/Readme.md
Closes: #75 
I have created a java file that implements a queue and then adds elements in the queue by add() method and removes the head element from the queue by remove() method.
<!-- ## How Has This Been Tested?
Run the code in Visual Studio code and have also given the output in the file itself.
> Added Queue Algo

- Tree/AVL_Trees/AVL_Tree.c
Issue Number : #78 
Closes: #78 
I have added the implementation of the AVL Tree along with sample output and Time Complexity in C Language.
I have verified it with sample input and output.
> Added AVL Tree implementation

- Stacks/Stack_Using_LInkedList.cpp
> Stack Using Linked List

- Graphs/Kosarajus_Algorithm/Kosarajus_Algorithm.cpp
#84 
Closes: #84 
I have implemented Kosaraju's Algorithm to find strongly connected components in C++.
I have verified it with sample input-output
> Added Kosaraju's Algorithm

- Sorting/BubbleSort/BubbleSort.c
The previous version had no implementation of bubble sort in C
Issue: #52 
Closes: #52
My version of code gives implementation of Bubble sort in C language via user input
<!-- ## How Has This Been Tested?
I have tested with sample input and output
> Added the bubble sort algorithm implementation in C

- Graphs/Krushkals_Algorithm/Krushkals_Algorithm.cpp
Issue: #85 
Closes: #85 85
I have implemented Krushkal's Algorithm to find MST.
I have tested it with sample input-output.
> Added Krushkal's Algorithm Implementation

- Sorting/Heap sort/heapsort.py
- Stacks/Stack Using Array.cpp
Sorting the elements using heap sort algo
- Closes: #97 
> Heap Sort.

- Sorting/Counting Sort/counting_sort.java
Closes: #[issue number that will be closed through this PR]
Adding Implementation of Counting Sort using Java
>  add java implementation of counting sort

- Searching/Linear_Search/linsear.py
- Closes: #[issue number that will be closed through this PR]
> Linear Search in Python

- Tree/Binary_Tree/Inorder_Traversal/inorder_traversal.cpp
- Tree/Binary_Tree/postorder_traversal/postorder_traversal.cpp
- Tree/Binary_Tree/preorder_Traversal/inorder_traversal.cpp
- Closes: #[issue number that will be closed through this PR]
> postorder Traversal of binary tree

- Tree/Binary_Tree/Inorder_Traversal/inorder_traversal.cpp
- Closes: #[issue number that will be closed through this PR]
> Inorder Traversal of Binary_Tree added

- Tree/Binary_Tree/Inorder_Traversal/inorder_traversal.cpp
- Tree/Binary_Tree/preorder_Traversal/inorder_traversal.cpp
- Closes: #[issue number that will be closed through this PR]
> Preorder Traversal of Binary Tree
